<?xml version="1.0" encoding="utf-8"?><Database Name="AdressBook" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-V4R7G9G\SQLEXPRESS;Initial Catalog=AdressBook;Integrated Security=True" SettingsObjectName="WindowsFormsApp5.Properties.Settings" SettingsPropertyName="AdressBookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BizContacts" Member="BizContacts">
    <Type Name="BizContact">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Beslutsdatum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Personnummer" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Förnamn" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Insatskategori" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Beslut" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Beslutsfattare" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Orsak" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Anteckningar" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>